### ISSUE TITLE
ModuleNotFoundError: No module named 'dill'

### ISSUE THREAD

**Issue by slackline** [jeshan/pytest-cleanup#1]
This looks like a very, very handy package as I'm utterly baffled by Test Driven Development.

Fresh install from PyPi and attempting to run results in...

```python
python -m pytest_cleanup wpweather    
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/neil/.virtualenvs/default/lib/python3.6/site-packages/pytest_cleanup/__init__.py", line 5, in <modu
le>                                                                                                             
    from .recorder import Recorder, get_test_data_filename, user_function
  File "/home/neil/.virtualenvs/default/lib/python3.6/site-packages/pytest_cleanup/recorder.py", line 12, in <mod
ule>                                                                                                            
    from pytest_cleanup.common import (
  File "/home/neil/.virtualenvs/default/lib/python3.6/site-packages/pytest_cleanup/common.py", line 4, in <module
>                                                                                                               
    import dill
ModuleNotFoundError: No module named 'dill'
```

Installing `dill` resolved this.  I'm not familiar with how you define requirements (used to seeing either `requirements.txt` or `setup.cfg` I'm still wet behind the ears in learning Python), otherwise I'd have made a PR to fix it.

**Comment by jeshan** [comment]
Hi, thanks so much for reporting this. My automated test should have picked that up but didn't.

>  I'm not familiar with how you define requirements

I'm using [flit](https://flit.readthedocs.io/) for the first time to package the artefact. I should have declared dill in pyproject.toml.

Try uninstalling dill and install pytest-cleanup release 0.4 and let me know!

**Comment by slackline** [comment]
Hi,

Thats worked, I created a new virtualenv and tried installing there and `dill` has been pulled in, however `pytest` isn't pulled in.

```
❱ mkvirtualenv test
Using base prefix '/usr'
New python3.6 executable in /home/neil/.virtualenvs/test/bin/python3.6
Not overwriting existing python3.6 script /home/neil/.virtualenvs/test/bin/python3.6 (you must use /home/neil/.virtualenvs/test/bin/python3.6)
Installing setuptools, pip, wheel...
done.
virtualenvwrapper.user_scripts creating /home/neil/.virtualenvs/test/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/neil/.virtualenvs/test/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/neil/.virtualenvs/test/bin/preactivate
virtualenvwrapper.user_scripts creating /home/neil/.virtualenvs/test/bin/postactivate
virtualenvwrapper.user_scripts creating /home/neil/.virtualenvs/test/bin/get_env_details
(test) ❱ pip install pytest-cleanup
Collecting pytest-cleanup
  Downloading pytest_cleanup-0.4-py2.py3-none-any.whl (15 kB)
Processing ./.cache/pip/wheels/59/b1/91/f02e76c732915c4015ab4010f3015469866c1eb9b14058d8e7/dill-0.3.1.1-cp36-none-any.whl
Collecting loguru<1
  Using cached loguru-0.4.1-py3-none-any.whl (54 kB)
Collecting jsonpickle<2
  Using cached jsonpickle-1.2-py2.py3-none-any.whl (32 kB)
Collecting aiocontextvars>=0.2.0; python_version < "3.7"
  Using cached aiocontextvars-0.2.2-py2.py3-none-any.whl (4.9 kB)
Processing ./.cache/pip/wheels/a5/7d/68/1ebae2668bda2228686e3c1cf16f2c2384cea6e9334ad5f6de/contextvars-2.4-cp36-none-any.whl
Collecting immutables>=0.9
  Using cached immutables-0.11-cp36-cp36m-manylinux1_x86_64.whl (92 kB)
Installing collected packages: dill, immutables, contextvars, aiocontextvars, loguru, jsonpickle, pytest-cleanup
Successfully installed aiocontextvars-0.2.2 contextvars-2.4 dill-0.3.1.1 immutables-0.11 jsonpickle-1.2 loguru-0.4.1 pytest-cleanup-0.4
(test) ❱ python -m pytest_cleanup 
2020-01-28 07:07:50.445 | DEBUG    | pytest_cleanup.constants:get_test_dir:18 - Will place test_pytestcleanup_cases.py under /home/neil
2020-01-28 07:07:50.445 | INFO     | pytest_cleanup.recorder:__init__:245 - creating instance of recorder
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/neil/.virtualenvs/test/lib/python3.6/site-packages/pytest_cleanup/__init__.py", line 6, in <module>
    from .runtime import parametrize_stg_tests
  File "/home/neil/.virtualenvs/test/lib/python3.6/site-packages/pytest_cleanup/runtime.py", line 9, in <module>
    from _pytest.python import Metafunc
ModuleNotFoundError: No module named '_pytest'
```

Thanks for the pointer on `flit` not come across that yet.

**Comment by jeshan** [comment]
Ok. Not putting dependency on pytest is deliberate; I wanted users to use
whatever pytest version they already have.
I will decide later this week whether I can add an optional dependency on
pytest.

This is valuable feedback.

**Comment by slackline** [comment]
Ok cool, thanks for your work on this and quick responses :+1:
